apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- api-gateway-rollout.yaml
- reporting-rollout.yaml
- corp-cockpit-rollout.yaml

commonLabels:
  deployment-strategy: blue-green
  part-of: teei-csr-platform
  managed-by: kustomize
