apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teei-platform

resources:
  - configmap.yaml
  - statefulset.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/component: logging
  app.kubernetes.io/part-of: teei-observability
