apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teei-platform

resources:
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-provisioning.yaml
  - grafana-secret.yaml
  - jaeger
  - loki
  - promtail

commonLabels:
  app.kubernetes.io/part-of: teei-observability
  component: observability
  managed-by: kustomize
