apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teei-platform

commonLabels:
  app: grafana
  component: observability
  managed-by: kustomize

resources:
- grafana-deployment.yaml
- grafana-service.yaml
- grafana-provisioning.yaml
- grafana-secret.yaml
