apiVersion: v1
kind: Service
metadata:
  name: teei-buddy-service
  labels:
    app: teei-buddy-service
    component: backend
    part-of: teei-csr-platform
spec:
  type: ClusterIP
  selector:
    app: teei-buddy-service
  ports:
  - name: http
    port: 80
    targetPort: 3003
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teei-buddy-service
  labels:
    app: teei-buddy-service
    component: backend
    part-of: teei-csr-platform
  annotations:
    vault.hashicorp.com/role: "teei-buddy-service"
