apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: http://teei-loki-headless:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        # Extract trace_id from logs to link to Jaeger
        - datasourceUid: jaeger-ds
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
        # Extract span_id from logs
        - datasourceUid: jaeger-ds
          matcherRegex: "span_id=(\\w+)"
          name: SpanID
          url: "$${__value.raw}"
