apiVersion: v1
kind: Service
metadata:
  name: teei-data-residency
  labels:
    app: teei-data-residency
    component: backend
    part-of: teei-csr-platform
spec:
  type: ClusterIP
  selector:
    app: teei-data-residency
  ports:
  - name: http
    port: 80
    targetPort: 3015
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teei-data-residency
  labels:
    app: teei-data-residency
    component: backend
    part-of: teei-csr-platform
  annotations:
    vault.hashicorp.com/role: "teei-data-residency"
