---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - namespace.yaml
  - istio-operator.yaml
  - istio-controlplane.yaml
  - gateway.yaml

labels:
  - pairs:
      part-of: teei-csr-platform
      component: service-mesh
