apiVersion: v1
kind: Service
metadata:
  name: teei-discord-bot
  labels:
    app: teei-discord-bot
    component: backend
    part-of: teei-csr-platform
spec:
  type: ClusterIP
  selector:
    app: teei-discord-bot
  ports:
  - name: http
    port: 80
    targetPort: 3009
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: teei-discord-bot
  labels:
    app: teei-discord-bot
    component: backend
    part-of: teei-csr-platform
  annotations:
    vault.hashicorp.com/role: "teei-discord-bot"
