apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- require-signed-images.yaml
- disallow-privileged-containers.yaml
- require-resource-limits.yaml
- require-read-only-root-filesystem.yaml
- require-run-as-non-root.yaml
- block-nodeport-services.yaml
- eu-data-residency-enforcement.yaml
