apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teei-platform

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: jaeger
  app.kubernetes.io/component: tracing
  app.kubernetes.io/part-of: teei-observability
