apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- q2q-ai-rollout.yaml
- analytics-rollout.yaml
- data-residency-rollout.yaml

commonLabels:
  deployment-strategy: canary
  part-of: teei-csr-platform
  managed-by: kustomize
