apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: teei-production

resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- pvc.yaml
- serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: privacy-orchestrator
  app.kubernetes.io/part-of: teei-platform
  app.kubernetes.io/managed-by: kustomize
