apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - hpa.yaml

commonLabels:
  app: teei-ai-budget
  component: finops
  part-of: teei-csr-platform
