apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway-rollout.yaml
- reporting-rollout.yaml

commonLabels:
  managed-by: argo-rollouts
  progressive-delivery: enabled
