apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
- namespace.yaml
- install.yaml
- dashboard.yaml
- crds.yaml

commonLabels:
  app.kubernetes.io/part-of: teei-csr-platform
  managed-by: kustomize
